apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

from apps.invoice.views import addData, editData, retrieveData

app_name = 'home'

urlpatterns = [

    path('invoice/', views.invoice, name='invoice'),
    path('contacts/', views.contacts, name='contactView'),
    path('patient/', views.patient, name='patientView'),

    path('addInvoice/',views.createInvoice, name='create-invoice'),
    path('inv/<slug:slug>',views.createBuildInvoice, name='create-build-invoice'),
    path('approve/<slug:slug>',views.approveInvoice, name='approve-invoice'),
    path('deleteItem/<slug:slug>/<slug:inv_slug>', views.deleteItem, name='delete-item'),
    path('deleteImg/<slug:inv_slug>', views.deleteImage, name='delete-image'),
    path('contact/', views.contact, name='contact'),
    path('addData/<str:model>', addData, name='addData'),
    path('editData/<str:model>/<int:dataID>', editData, name='editData'),
    path('retrieve/<str:model>/<int:dataID>', retrieveData, name='retrieveData'),
    path('contact/<slug:slug>/<slug:req>', views.get_contact, name='get-contact'),

    path('', views.index, name='home'),

    path('p/<slug:slug>/', views.PageView.as_view(), name='page_details'),

    re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

s/invoicing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from invoice import views as invoice_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #INVOICE URLS
    path('', invoice_views.index, name='index'),
    path('invoice/',include('invoice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/invoice/models.py
from operator import mod
from tkinter import CASCADE
from uuid import uuid4
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Company(models.Model):
    # Basic Fields
    name = models.CharField(null=True, blank=True, max_length=200, verbose_name='اسم الشركة')
    commercialRegister = models.IntegerField(null=True, blank=True, unique=True, verbose_name='رقم السجل التجاري')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return '%s | رقم السجل التجاري: %s' % (self.name, self.commercialRegister)
    
    def get_absolute_url(self):
        return reverse('company-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {} {}'.format(self.name, self.commercialRegister, self.uniqueId))
        self.slug = slugify('{} {} {}'.format(self.name, self.commercialRegister, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Company, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'شركة'
        verbose_name_plural = 'شركات'


class Category(models.Model):
    # Basic Fields
    name = models.CharField(null=True, blank=True, max_length=200, verbose_name='تصنيف')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('category-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Category, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'تصنيف'
        verbose_name_plural = 'تصنيفات'
        

class Department(models.Model):
    # Basic Fields
    name = models.CharField(null=True, blank=True, max_length=200, verbose_name='قسم')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('department-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Department, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'قسم'
        verbose_name_plural = 'أقسام'


class Invoice(models.Model):
    STATE = (
        (1, 'في المشتريات'),
        (2, 'في الأمن'),
        (3, 'في الماليات'),
        (4, 'في الإدارة'),
        (5, 'منتهية')
    )
    # Basic Fields
    number = models.CharField(null=True, blank=True, max_length=100, verbose_name='رقم الفاتورة')
    entryPerson = models.CharField(null=True, blank=True, max_length=100, verbose_name='إدخال البيانات')
    purchase_date = models.DateField(null=True, blank=True, verbose_name='تاريخ الشراء')
    current_state = models.SmallIntegerField(null=True, blank=True, verbose_name='حالة الفاتورة الحالية', choices=STATE, default=1)
    img = models.ImageField(null=True, blank=True, upload_to='apps/media/inv_images')
    # Related Fields
    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.PROTECT, verbose_name='اسم الشركة')
    department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.PROTECT, verbose_name='موجه للقسم')
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.PROTECT, verbose_name='تصنيف الفاتورة')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100, default=None)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True, default=None)
    last_updated = models.DateTimeField(blank=True, null=True, default=None)
    def __str__(self) -> str:
        return '%s | #فاتورة %s' % (self.company, self.number)
    def get_absolute_url(self):
        return reverse('invoice-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{}'.format(self.uniqueId))
        self.slug = slugify('{}'.format(self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Invoice, self).save(*args, **kwargs)
    class Meta:
        unique_together = ['number', 'company']
        permissions = [
            ("it", "نظم المعلومات"),
            ("purchase", "مكتب المشتريات"),
            ("finance", "الماليات"),
            ("director", "المدير"),
            ("security", "الأمن"),
        ]
        verbose_name = 'فاتورة'
        verbose_name_plural = 'فواتير'


class Item(models.Model):
    # Basic Fields
    name = models.CharField(max_length=200, verbose_name='صنف')
    description = models.CharField(max_length=200, verbose_name='وصف', default="-")
    quantity = models.FloatField(verbose_name='الكمية')
    price = models.FloatField(verbose_name='سعر الوحدة')
    # Related Fields
    invoice = models.ForeignKey(Invoice, blank=True, null=True, on_delete=models.CASCADE, verbose_name='الفاتورة')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    total_price = models.FloatField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        self.total_price = self.quantity * self.price
        super(Item, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'صنف'
        verbose_name_plural = 'أصناف'


class Comment(models.Model):
    # Basic Fields
    detail = models.CharField(null=False, blank=False, max_length=200, verbose_name='ملاحظة')
    entryPerson = models.CharField(null=True, blank=True, max_length=100, verbose_name='إدخال البيانات')
    # Related Fields
    invoice = models.ForeignKey(Invoice, blank=True, null=True, on_delete=models.CASCADE, verbose_name='الفاتورة')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    date_created = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('comment-detail', kwargs={'id': self.uniqueId})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
        super(Comment, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'ملاحظة'
        verbose_name_plural = 'ملاحظات'

# # For Reference ...
# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date =  models.DateTimeField('date published')
    
#     def __str__(self) -> str:
#         return self.question_text

#     @admin.display(
#         boolean=True,
#         ordering='pub_date',
#         description='Published recently?',
#     )
#     def was_published_recently(self):
#         return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now()
        
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

#     def __str__(self) -> str:
#         return self.choice_text

apps/templates/patient/navigation.html
	<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">		
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#"><span></span></a>
            <a href="{% url 'home:invoice' %}" class="b-brand">
                منظومة الأرشيف الإلكتروني
            </a>
            <a href="#" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    الحساب المستخدم حالياً: {{ user.first_name }}/ {{ user.last_name }}
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li>
                    <a href="{% url 'logout' %}" class="dropdown-item">
                        تسجيل خروج
                        <i class="feather icon-log-out ms-1"></i>
                    </a>
                </li>
            </ul>
        </div>
</header>

apps/templates/patient/sidebar.html
	{% comment %} [ navigation menu ] start {% endcomment %}
	<nav class="pcoded-navbar menupos-fixed menu-light ">
		<div class="navbar-wrapper">
			<div class="navbar-content scroll-div ">
				<ul class="nav pcoded-inner-navbar ">
					<li class="nav-item pcoded-menu-caption">
						<label>تنقل</label>
					</li>

					{% comment %} General Section: All groups have permission to view this section! {% endcomment %}
					<li class="nav-item">
						<a href="{% url 'home:patientView' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-eye"></i></span>
							<span class="pcoded-mtext">نظرة عامة</span>
						</a>
					</li>
					{% comment %} End of General Section {% endcomment %}

					{% comment %} IT Section: IT group has permission to view this section! {% endcomment %}
					{% if perms.invoice.it %}
					<li class="nav-item pcoded-menu-caption">
						<label>إدارة بيانات المنظومة</label>
					</li>
					<li class="nav-item">
						<a href="/add-company.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-plus-square"></i></span>
							<span class="pcoded-mtext">إضافة شركة</span>
						</a>
					</li>
					<li class="nav-item">
						<a href="/list-company.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-list" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">قائمة الشركات</span>
						</a>
					</li>
					{% endif %}
					{% comment %} End of Purchase Section {% endcomment %}

					{% comment %} Patient Affairs Section: Purchasing Office group has permission to view this section! {% endcomment %}
					{% if perms.invoice.purchase %}
					<li class="nav-item pcoded-menu-caption">
						<label>إدخال الملفات</label>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:create-invoice' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-plus-square"></i></span>
							<span class="pcoded-mtext">إضافة ملف</span>
						</a>
					</li>
					{% endif %}
					{% comment %} End of Patient Affairs Section {% endcomment %}

					{% comment %} Archive Section: Managers group has permission to view this section! {% endcomment %}
					{% if perms.invoice.director %}
					<li class="nav-item pcoded-menu-caption">
						<label>أرشيف المرضى</label>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-layers" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">عرض كافة الملفات</span>
						</a>
					</li>
					<li class="nav-item pcoded-hasmenu">
						<a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-clock"></i></span>
							<span class="pcoded-mtext">عرض حسب التوقيت</span>
						</a>
						<ul class="pcoded-submenu">
							<li class="pcoded-hasmenu">
								<a href="#">آخر فترة</a>
								<ul class="pcoded-submenu">
									<li><a href="#">7 أيام</a></li>
									<li><a href="#">30 يوم</a></li>
									<li><a href="#">90 يوم</a></li>
								</ul>
							</li>
							<li class="pcoded-hasmenu">
								<a href="#">خلال مدة</a>
								<ul class="pcoded-submenu">
									<li><a href="#">الشهر الحالي</a></li>
									<li><a href="#">الشهر السابق</a></li>
									<li><a href="#">السنة الحالية</a></li>
									<li><a href="#">السنة السابقة</a></li>
								</ul>
							</li>
						</ul>
					</li>
					{% endif %}
					{% comment %} End of Archive Section {% endcomment %}

					{% comment %} Systems Section: Managers & IT groups has permission to view this section! {% endcomment %}
					{% if perms.invoice.director or perms.invoice.it %}
					<li class="nav-item pcoded-menu-caption">
						<label>شبكة نظم المعلومات</label>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:contactView' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-message-square" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">منظومة التواصل الإلكتروني</span>
						</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:invoice' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-package" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">منظومة الفواتير الإلكترونية</span>
						</a>
					</li>
					{% endif %}
					{% comment %} End of Systems Section {% endcomment %}

					<li class="nav-item mt-5">
						<a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
							<span class="pcoded-mtext">عودة للصفحة الرئيسية</span>
						</a>
					</li>
					
				</ul>
			</div>
		</div>
	</nav>
	{% comment %} [ navigation menu ] end {% endcomment %}
    