apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

from apps.invoice.views import addData, editData, retrieveData

app_name = 'home'

urlpatterns = [

    path('invoice/', views.invoice, name='invoice'),
    path('contacts/', views.contacts, name='contactView'),
    path('patient/', views.patient, name='patientView'),

    path('addInvoice/',views.createInvoice, name='create-invoice'),
    path('inv/<slug:slug>',views.createBuildInvoice, name='create-build-invoice'),
    path('approve/<slug:slug>',views.approveInvoice, name='approve-invoice'),
    path('deleteItem/<slug:slug>/<slug:inv_slug>', views.deleteItem, name='delete-item'),
    path('deleteImg/<slug:inv_slug>', views.deleteImage, name='delete-image'),
    path('contact/', views.contact, name='contact'),
    path('addData/<str:model>', addData, name='addData'),
    path('editData/<str:model>/<int:dataID>', editData, name='editData'),
    path('retrieve/<str:model>/<int:dataID>', retrieveData, name='retrieveData'),
    path('contact/<slug:slug>/<slug:req>', views.get_contact, name='get-contact'),

    path('', views.index, name='home'),

    path('p/<slug:slug>/', views.PageView.as_view(), name='page_details'),

    re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

s/invoicing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from invoice import views as invoice_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #INVOICE URLS
    path('', invoice_views.index, name='index'),
    path('invoice/',include('invoice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/contacts/list-contact.html
{% extends "layouts/base-contacts.html" %}

{% block title %} نماذج التواصل {% endblock %} 

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	<!-- [ Main Content ] start -->
	<div class="pcoded-main-container">
		<div class="pcoded-content">
			<!-- [ breadcrumb ] start -->
			<div class="page-header">
				<div class="page-block">
					<div class="row align-items-center">
						<div class="col-md-12">
							<div class="page-header-title">
								<h5 class="m-b-10">قائمة {{ contact_type }}</h5>
							</div>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
								<li class="breadcrumb-item"><a href="#">نماذج التواصل</a></li>
								<li class="breadcrumb-item"><a href="#">{{ contact_type }}</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<!-- [ breadcrumb ] end -->
			<!-- [ Main Content ] start -->
			<div class="row">
				<!-- [ sample-page ] start -->
				<div class="col-sm-12">
					<div class="card">
						<div class="card-header">
							<h5>
								قائمة 
								{{ contact_type }}
								المقدمة من خلال نماذج التواصل
							</h5>
						</div>
						<div class="card-body table-border-style">
							{% if contact_req == "all" %}
							<ul class="feed-blog ps-0">
                                {% for contact in contact_list %}
                                <li class="active-feed">
                                    <div class="feed-user-img">
                                        <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius " alt="User-Profile-Image">
                                    </div>
                                    <h6>
                                        {% if contact.msg_type == 'suggest' %}
                                        <span class="badge bg-success">مقترح</span>
                                        {% endif %}
                                        {% if contact.msg_type == 'complain' %}
                                        <span class="badge bg-danger">شكوى</span>
                                        {% endif %}
                                        من 
                                        <span class="text-c-blue">{{ contact.name }}</span>
                                        | تابع لـ
                                        <span class="text-c-blue">{{ contact.department }}</span>
                                        |
                                        <small class="text-muted">{{ contact.msg_created }}</small>
										<span class="float-end">
											<a href="s{{contact.id}}">
												{% if not contact.msg_flag %}
												<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
													<path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288L8 2.223l1.847 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.565.565 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
												</svg>
												{% else %}
												<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
													<path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
												</svg>
												{% endif %}
											</a>
										</span>
                                    </h6>
                                    <p class="m-b-15 m-t-15">{{ contact.msg_text }}</p>
                                </li>
                                {% endfor %}
                            </ul>
							{% elif contact_req == "filter" %}
							<h4>
								<i class="feather icon-chevrons-left" aria-hidden="true"></i> 
								<a href="{% url 'home:get-contact' slug=contact_slug req='all' %}">
									عرض كافة {{ contact_type }}
								</a>
							</h4>
							<div class="accordion accordion-flush">
								<div class="accordion-item mt-3">
									<h2 class="accordion-header" id="flush-headingOne">
										<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
											<i class="feather icon-filter me-1" aria-hidden="true"></i>
											ترشيح حسب القسم
										</button>
									</h2>
									<div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
										<div class="accordion-body">
											<table class="table table-hover">
												<tbody>
													{% for department in department_list %}<tr>
														<td>
															<i class="feather icon-chevron-left" aria-hidden="true"></i>
															<a href="{{ department.id }}">
																{{ department }}
															</a>
														</td>
													</tr>{% endfor %}
												</tbody>
											</table>
										</div>
									</div>
								</div>
								<div class="accordion-item mt-3">
									<h2 class="accordion-header" id="flush-headingTwo">
										<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
											<i class="feather icon-filter me-1" aria-hidden="true"></i>
											ترشيح حسب التوقيت
										</button>
									</h2>
									<div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
										<div class="accordion-body">
											<table class="table table-hover">
												<tbody>
													<tr>
														<td>
															<i class="feather icon-chevron-left" aria-hidden="true"></i>
															<a href="d7">
																آخر 7 أيام
															</a>
														</td>
													</tr>
													<tr>
														<td>
															<i class="feather icon-chevron-left" aria-hidden="true"></i>
															<a href="d30">
																آخر 30 يوم
															</a>
														</td>
													</tr>
													<tr>
														<td>
															<i class="feather icon-chevron-left" aria-hidden="true"></i>
															<a href="d90">
																آخر 90 يوم
															</a>
														</td>
													</tr>
												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
							{% else %}
							<h5><i class="feather icon-chevrons-left" aria-hidden="true"></i>  {{ contact_department }}</h5>
							<ul class="feed-blog ps-0 mt-4">
								{% if not contact_list %}
								لا يوجد عناصر
								{% else %}
                                {% for contact in contact_list %}
                                <li class="active-feed">
                                    <div class="feed-user-img">
                                        <img src="/static/assets/images/user/avatar-1.jpg" class="img-radius " alt="User-Profile-Image">
                                    </div>
                                    <h6>
                                        {% if contact.msg_type == 'suggest' %}
                                        <span class="badge bg-success">مقترح</span>
                                        {% endif %}
                                        {% if contact.msg_type == 'complain' %}
                                        <span class="badge bg-danger">شكوى</span>
                                        {% endif %}
                                        من 
                                        <span class="text-c-blue">{{ contact.name }}</span>
                                        | تابع لـ
                                        <span class="text-c-blue">{{ contact.department }}</span>
                                        |
                                        <small class="text-muted">{{ contact.msg_created }}</small>
                                    </h6>
                                    <p class="m-b-15 m-t-15">{{ contact.msg_text }}</p>
                                </li>
                                {% endfor %}
								{% endif %}
                            </ul>
							{% endif %}
                        </div>
					</div>
				</div>
				<!-- [ sample-page ] end -->
			</div>
			<!-- [ Main Content ] end -->
		</div>
	</div>
	<!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/contacts/navigation.html
	<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-blue">		
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#"><span></span></a>
            <a href="{% url 'home:invoice' %}" class="b-brand">
                منظومة التواصل الإلكتروني
            </a>
            <a href="#" class="mob-toggler">
                <i class="feather icon-more-vertical"></i>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    الحساب المستخدم حالياً: {{ user.first_name }}/ {{ user.last_name }}
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li>
                    <a href="{% url 'logout' %}" class="dropdown-item">
                        تسجيل خروج
                        <i class="feather icon-log-out ms-1"></i>
                    </a>
                </li>
            </ul>
        </div>
</header>

apps/templates/contacts/sidebar.html
	{% comment %} [ navigation menu ] start {% endcomment %}
	<nav class="pcoded-navbar menupos-fixed menu-light ">
		<div class="navbar-wrapper">
			<div class="navbar-content scroll-div ">
				<ul class="nav pcoded-inner-navbar ">
					<li class="nav-item pcoded-menu-caption">
						<label>تنقل</label>
					</li>

					{% comment %} General Section: All groups have permission to view this section! {% endcomment %}
					<li class="nav-item">
						<a href="{% url 'home:contactView' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-eye"></i></span>
							<span class="pcoded-mtext">نظرة عامة</span>
						</a>
					</li>
					{% comment %} End of General Section {% endcomment %}

					{% comment %} IT Section: IT group has permission to view this section! {% endcomment %}
					{% if perms.invoice.it %}
					<li class="nav-item pcoded-menu-caption">
						<label>إدارة نماذج التواصل</label>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-plus-square"></i></span>
							<span class="pcoded-mtext">استعادة نموذج</span>
						</a>
					</li>
					<li class="nav-item">
						<a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-minus-square" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">حذف نموذج</span>
						</a>
					</li>
					{% endif %}
					{% comment %} End of Purchase Section {% endcomment %}

					{% comment %} Manager Section: Managers group has permission to view this section! {% endcomment %}
					{% if perms.invoice.director %}
					
					<li class="nav-item pcoded-menu-caption">
						<label>نماذج التواصل</label>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:get-contact' slug='star' req='all' %}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-star" style="color:darkgoldenrod"></i></span>
							<span class="pcoded-mtext">نماذج مميزة</span>
						</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:get-contact' slug='suggest' req='filter' %}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-info" style="color:darkgreen"></i></span>
							<span class="pcoded-mtext">المقترحات</span>
						</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:get-contact' slug='complain' req='filter' %}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-minus-circle" style="color:darkred"></i></span>
							<span class="pcoded-mtext">الشكاوى</span>
						</a>
					</li>
					{% endif %}
					{% comment %} End of Manager Section {% endcomment %}

					{% comment %} Systems Section: Managers & IT groups has permission to view this section! {% endcomment %}
					{% if perms.invoice.director or perms.invoice.it %}
					<li class="nav-item pcoded-menu-caption">
						<label>شبكة نظم المعلومات</label>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:invoice' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-message-square" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">منظومة الفواتير الإلكترونية</span>
						</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'home:patientView' %}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-package" aria-hidden="true"></i></span>
							<span class="pcoded-mtext">منظومة الأرشيف الإلكتروني</span>
						</a>
					</li>
					{% endif %}
					{% comment %} End of Systems Section {% endcomment %}

					<li class="nav-item mt-5">
						<a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span>
							<span class="pcoded-mtext">عودة للصفحة الرئيسية</span>
						</a>
					</li>
					
				</ul>
			</div>
		</div>
	</nav>
	{% comment %} [ navigation menu ] end {% endcomment %}
    