apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

from apps.invoice.views import addData, editData, retrieveData

app_name = 'home'

urlpatterns = [

    path('invoice/', views.invoice, name='invoice'),
    path('contacts/', views.contacts, name='contactView'),
    path('patient/', views.patient, name='patientView'),

    path('addInvoice/',views.createInvoice, name='create-invoice'),
    path('inv/<slug:slug>',views.createBuildInvoice, name='create-build-invoice'),
    path('approve/<slug:slug>',views.approveInvoice, name='approve-invoice'),
    path('deleteItem/<slug:slug>/<slug:inv_slug>', views.deleteItem, name='delete-item'),
    path('deleteImg/<slug:inv_slug>', views.deleteImage, name='delete-image'),
    path('contact/', views.contact, name='contact'),
    path('addData/<str:model>', addData, name='addData'),
    path('editData/<str:model>/<int:dataID>', editData, name='editData'),
    path('retrieve/<str:model>/<int:dataID>', retrieveData, name='retrieveData'),
    path('contact/<slug:slug>/<slug:req>', views.get_contact, name='get-contact'),

    path('', views.index, name='home'),

    path('p/<slug:slug>/', views.PageView.as_view(), name='page_details'),

    re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

s/invoicing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from invoice import views as invoice_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #INVOICE URLS
    path('', invoice_views.index, name='index'),
    path('invoice/',include('invoice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/includes/footer.html
    <footer class="container my-5 pb-5">
        <hr class="mb-5">
        <p class="float-start"><a href="#"><i class="fa fa-arrow-circle-up" aria-hidden="true" style="font-size:2.5rem"></i></a></p>
        <p class="float-end"><span>المستشفى العسكري بدمياط الجديدة &copy; 2022 &middot; جميع الحقوق محفوظة &middot; </span><a href="{% url 'admin:index' %}" target="_blank">لوحة التحكم</a></p>
        <div class="d-block" style="clear: both;">
            &middot; تصميم وبرمجة: <a href="https://www.linkedin.com/in/abdolla25/" target="_blank">م. عبدالله زهران</a> &middot; بواسطة فرع النظم &middot; 
        </div>
    </footer>

apps/templates/includes/navigation.html
<header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home:home' %}">
                    <img id="logo" src="/static/assets/images/logoHQ.png" alt="المستشفى العسكري بدمياط الجديدة">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mb-2 mb-lg-0">
                        {% for menu_item in menu_items %}
                        {% if menu_item.has_sub %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                {{ menu_item.page_name }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for submenu_item in submenu_list %}
                                {% if submenu_item.parent.page_name == menu_item.page_name %}
                                <li><a class="dropdown-item" href="/p{{ submenu_item.sub_page_url }}">{{ submenu_item.sub_page_name }}</a></li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/p{{ menu_item.page_url }}">{{ menu_item.page_name }}</a>
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                    {% if user.is_authenticated %}
                    <a href="{% url 'home:invoice' %}">
                        <button type="button" class="btn btn-outline-danger">
                            شبكة نظم المعلومات
                            <i class="fa fa-external-link me-1" aria-hidden="true"></i>
                        </button>
                    </a>
                    <a href="{% url 'logout' %}">
                        أهلاً, {{ user.last_name }} اضغط للخروج
                        <i class="fa fa-sign-out me-1" aria-hidden="true"></i>
                        </button>
                    </a>
                    {% else %}
                    <a href="{% url 'home:invoice' %}">
                        <button type="button" class="btn btn-outline-danger">
                            تسجيل الدخول
                            <i class="fa fa-sign-in me-1" aria-hidden="true"></i>
                        </button>
                    </a>
                    {% endif %}
                    <form class="d-flex" action="/search" method="get">
                        <input name="q" class="form-control ms-2" type="text" placeholder="بحث في الموقع" aria-label="Search">
                        <button class="btn btn-outline-primary" type="submit">بحث</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

apps/templates/includes/scripts.html
    <script src="/static/assets/js/plugins/popper.min.js"></script>
    <script src="/static/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="/static/assets/js/plugins/bootstrap.min.js"></script>
    <script src="/static/assets/js/pcoded.js"></script>
    

apps/templates/includes/sidebar.html
	<!-- [ navigation menu ] start -->
	<nav class="pcoded-navbar menupos-fixed menu-light ">
		<div
			class="navbar-wrapper  ">
			<div class="navbar-content scroll-div "
				>
				<ul class="nav pcoded-inner-navbar ">
					<li class="nav-item pcoded-menu-caption">
						<label>Navigation</label>
					</li>
					<li class="nav-item">
						<a href="/" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span
								class="pcoded-mtext">Dashboard</span></a>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>UI Element</label>
					</li>
					<li class="nav-item">
						<a href="/bc_typography.html" class="nav-link "><span class="pcoded-micon"><i
									class="feather icon-box"></i></span><span class="pcoded-mtext">Typography</span></a>
					</li>
					<li class="nav-item">
						<a href="/icon-feather.html" class="nav-link "><span class="pcoded-micon"><i
									class="feather icon-feather"></i></span><span class="pcoded-mtext">Icons</span></a>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>table</label>
					</li>
					<li class="nav-item">
						<a href="/tbl_bootstrap.html" class="nav-link "><span class="pcoded-micon"><i
									class="feather icon-align-justify"></i></span><span class="pcoded-mtext">Bootstrap table</span></a>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>Chart & Maps</label>
					</li>
					<li class="nav-item">
						<a href="/chart-apex.html" class="nav-link "><span class="pcoded-micon"><i
									class="feather icon-pie-chart"></i></span><span class="pcoded-mtext">Chart</span></a>
					</li>
					<li class="nav-item">
						<a href="/map-google.html" class="nav-link "><span class="pcoded-micon"><i class="feather icon-map"></i></span><span
								class="pcoded-mtext">Maps</span></a>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>Pages</label>
					</li>
					<li class="nav-item pcoded-hasmenu">
						<a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span
								class="pcoded-mtext">Authentication</span></a>
						<ul class="pcoded-submenu">
							<li><a href="/auth-signup.html" target="_blank">Sign up</a></li>
							<li><a href="/auth-signin.html" target="_blank">Sign in</a></li>
						</ul>
					</li>
					<li class="nav-item pcoded-menu-caption">
						<label>Other</label>
					</li>
					<li class="nav-item pcoded-hasmenu">
						<a href="#" class="nav-link "><span class="pcoded-micon"><i class="feather icon-menu"></i></span><span
								class="pcoded-mtext">Menu levels</span></a>
						<ul class="pcoded-submenu">
							<li><a href="#">Menu Level 2.1</a></li>
							<li class="pcoded-hasmenu">
								<a href="#">Menu level 2.2</a>
								<ul class="pcoded-submenu">
									<li><a href="#">Menu level 3.1</a></li>
									<li><a href="#">Menu level 3.2</a></li>
								</ul>
							</li>
						</ul>
					</li>
					<li class="nav-item"><a href="/sample-page.html" class="nav-link "><span class="pcoded-micon"><i
									class="feather icon-sidebar"></i></span><span class="pcoded-mtext">Sample page</span></a></li>
				</ul>
				
				<div class="card text-center">
					<div class="card-body px-3">
						<i class="feather icon-sunset f-40"></i>
						<h6 class="mt-3">Upgrade to Pro</h6>
						<p>To get more features and components</p>
						<a href="https://appseed.us/product/gradient-able-pro/django/" target="_blank"
							class="btn btn-primary btn-sm text-white m-0">Buy now</a>
					</div>
				</div>
				
			</div>
		</div>
	</nav>
	<!-- [ navigation menu ] end -->
    