apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

from apps.invoice.views import addData, editData, retrieveData

app_name = 'home'

urlpatterns = [

    path('invoice/', views.invoice, name='invoice'),
    path('contacts/', views.contacts, name='contactView'),
    path('patient/', views.patient, name='patientView'),

    path('addInvoice/',views.createInvoice, name='create-invoice'),
    path('inv/<slug:slug>',views.createBuildInvoice, name='create-build-invoice'),
    path('approve/<slug:slug>',views.approveInvoice, name='approve-invoice'),
    path('deleteItem/<slug:slug>/<slug:inv_slug>', views.deleteItem, name='delete-item'),
    path('deleteImg/<slug:inv_slug>', views.deleteImage, name='delete-image'),
    path('contact/', views.contact, name='contact'),
    path('addData/<str:model>', addData, name='addData'),
    path('editData/<str:model>/<int:dataID>', editData, name='editData'),
    path('retrieve/<str:model>/<int:dataID>', retrieveData, name='retrieveData'),
    path('contact/<slug:slug>/<slug:req>', views.get_contact, name='get-contact'),

    path('', views.index, name='home'),

    path('p/<slug:slug>/', views.PageView.as_view(), name='page_details'),

    re_path(r'^.*\.*', views.pages, name='pages'),

]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

s/invoice/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('login',views.login, name='login'),
path('logout',views.logout, name='logout'),
path('dashboard',views.dashboard, name='dashboard'),
path('invoices',views.invoices, name='invoices'),
path('products',views.products, name='products'),
path('clients',views.clients, name='clients'),

#Create URL Paths
path('invoices/create',views.createInvoice, name='create-invoice'),
path('invoices/create-build/<slug:slug>',views.createBuildInvoice, name='create-build-invoice'),

#Delete an invoice
path('invoices/delete/<slug:slug>',views.deleteInvoice, name='delete-invoice'),

#PDF and EMAIL Paths
path('invoices/view-pdf/<slug:slug>',views.viewPDFInvoice, name='view-pdf-invoice'),
path('invoices/view-document/<slug:slug>',views.viewDocumentInvoice, name='view-document-invoice'),
path('invoices/email-document/<slug:slug>',views.emailDocumentInvoice, name='email-document-invoice'),

#Company Settings Page
path('company/settings',views.companySettings, name='company-settings'),
]

s/invoicing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf import settings
from django.conf.urls.static import static

from invoice import views as invoice_views

urlpatterns = [
    path('admin/', admin.site.urls),

    #INVOICE URLS
    path('', invoice_views.index, name='index'),
    path('invoice/',include('invoice.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/invoice/models.py
from operator import mod
from tkinter import CASCADE
from uuid import uuid4
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from django.contrib import admin

# Create your models here.

class Company(models.Model):
    # Basic Fields
    name = models.CharField(null=True, blank=True, max_length=200, verbose_name='اسم الشركة')
    commercialRegister = models.IntegerField(null=True, blank=True, unique=True, verbose_name='رقم السجل التجاري')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return '%s | رقم السجل التجاري: %s' % (self.name, self.commercialRegister)
    
    def get_absolute_url(self):
        return reverse('company-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {} {}'.format(self.name, self.commercialRegister, self.uniqueId))
        self.slug = slugify('{} {} {}'.format(self.name, self.commercialRegister, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Company, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'شركة'
        verbose_name_plural = 'شركات'


class Category(models.Model):
    # Basic Fields
    name = models.CharField(null=True, blank=True, max_length=200, verbose_name='تصنيف')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('category-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Category, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'تصنيف'
        verbose_name_plural = 'تصنيفات'
        

class Department(models.Model):
    # Basic Fields
    name = models.CharField(null=True, blank=True, max_length=200, verbose_name='قسم')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('department-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Department, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'قسم'
        verbose_name_plural = 'أقسام'


class Invoice(models.Model):
    STATE = (
        (1, 'في المشتريات'),
        (2, 'في الأمن'),
        (3, 'في الماليات'),
        (4, 'في الإدارة'),
        (5, 'منتهية')
    )
    # Basic Fields
    number = models.CharField(null=True, blank=True, max_length=100, verbose_name='رقم الفاتورة')
    entryPerson = models.CharField(null=True, blank=True, max_length=100, verbose_name='إدخال البيانات')
    purchase_date = models.DateField(null=True, blank=True, verbose_name='تاريخ الشراء')
    current_state = models.SmallIntegerField(null=True, blank=True, verbose_name='حالة الفاتورة الحالية', choices=STATE, default=1)
    img = models.ImageField(null=True, blank=True, upload_to='apps/media/inv_images')
    # Related Fields
    company = models.ForeignKey(Company, null=True, blank=True, on_delete=models.PROTECT, verbose_name='اسم الشركة')
    department = models.ForeignKey(Department, null=True, blank=True, on_delete=models.PROTECT, verbose_name='موجه للقسم')
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.PROTECT, verbose_name='تصنيف الفاتورة')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100, default=None)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True, default=None)
    last_updated = models.DateTimeField(blank=True, null=True, default=None)
    def __str__(self) -> str:
        return '%s | #فاتورة %s' % (self.company, self.number)
    def get_absolute_url(self):
        return reverse('invoice-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{}'.format(self.uniqueId))
        self.slug = slugify('{}'.format(self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        super(Invoice, self).save(*args, **kwargs)
    class Meta:
        unique_together = ['number', 'company']
        permissions = [
            ("it", "نظم المعلومات"),
            ("purchase", "مكتب المشتريات"),
            ("finance", "الماليات"),
            ("director", "المدير"),
            ("security", "الأمن"),
        ]
        verbose_name = 'فاتورة'
        verbose_name_plural = 'فواتير'


class Item(models.Model):
    # Basic Fields
    name = models.CharField(max_length=200, verbose_name='صنف')
    description = models.CharField(max_length=200, verbose_name='وصف', default="-")
    quantity = models.FloatField(verbose_name='الكمية')
    price = models.FloatField(verbose_name='سعر الوحدة')
    # Related Fields
    invoice = models.ForeignKey(Invoice, blank=True, null=True, on_delete=models.CASCADE, verbose_name='الفاتورة')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True)
    last_updated = models.DateTimeField(blank=True, null=True)
    total_price = models.FloatField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'slug': self.slug})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
            self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.slug = slugify('{} {}'.format(self.name, self.uniqueId))
        self.last_updated = timezone.localtime(timezone.now())
        self.total_price = self.quantity * self.price
        super(Item, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'صنف'
        verbose_name_plural = 'أصناف'


class Comment(models.Model):
    # Basic Fields
    detail = models.CharField(null=False, blank=False, max_length=200, verbose_name='ملاحظة')
    entryPerson = models.CharField(null=True, blank=True, max_length=100, verbose_name='إدخال البيانات')
    # Related Fields
    invoice = models.ForeignKey(Invoice, blank=True, null=True, on_delete=models.CASCADE, verbose_name='الفاتورة')
    # Utility Fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    date_created = models.DateTimeField(blank=True, null=True)
    def __str__(self) -> str:
        return self.name
    def get_absolute_url(self):
        return reverse('comment-detail', kwargs={'id': self.uniqueId})
    def save(self, *args, **kwargs):
        if self.date_created is None:
            self.date_created = timezone.localtime(timezone.now())
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
        super(Comment, self).save(*args, **kwargs)
    class Meta:
        verbose_name = 'ملاحظة'
        verbose_name_plural = 'ملاحظات'

# # For Reference ...
# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date =  models.DateTimeField('date published')
    
#     def __str__(self) -> str:
#         return self.question_text

#     @admin.display(
#         boolean=True,
#         ordering='pub_date',
#         description='Published recently?',
#     )
#     def was_published_recently(self):
#         return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= timezone.now()
        
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)

#     def __str__(self) -> str:
#         return self.choice_text

apps/invoice/views.py
from tokenize import Name
from unicodedata import name
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template import loader

from apps.invoice.forms import AddCategoryForm, AddCompanyForm, AddDepartmentForm, AddInvoiceForm

from django.contrib import messages

from apps.invoice.models import Category, Company, Department

# Create your views here.
def retrieveData(request, model, dataID):
    context = {}
    targetModel = model
    targetID = dataID
    if (targetModel == 'company'):
        context['company_data'] = Company.objects.get(id=targetID)
    elif (targetModel == 'category'):
        context['category_data'] = Category.objects.get(id=targetID)
    elif (targetModel == 'department'):
        context['department_data'] = Department.objects.get(id=targetID)
    html_template = loader.get_template('invoice/edit-{}.html'.format(targetModel))
    return HttpResponse(html_template.render(context, request))

def editData(request, model, dataID):
    targetModel = model
    targetID = dataID
    AddForms = {'company': AddCompanyForm, 'category': AddCategoryForm, 'department': AddDepartmentForm}
    if request.method == 'POST':
        form = AddForms[model](request.POST)
        try:
            if (targetModel == 'company'):
                Company.objects.filter(id=targetID).update(name=form['name'].value())
                Company.objects.filter(id=targetID).update(commercialRegister=form['commercialRegister'].value())
                messages.success(request, 'تم تعديل البيانات بنجاح!')
            elif (targetModel == 'category'):
                Category.objects.filter(id=targetID).update(name=form['name'].value())
                messages.success(request, 'تم تعديل البيانات بنجاح!')
            elif (targetModel == 'department'):
                Department.objects.filter(id=targetID).update(name=form['name'].value())
                messages.success(request, 'تم تعديل البيانات بنجاح!')
        except:
            messages.warning(request, 'لم يتم تعديل البيانات، يرجى مراجعة نوع وقيمة البيانات المدخلة!')
        # if a GET (or any other method) we'll create a blank form
    else:
        messages.warning(request, 'لم يتم تعديل البيانات، يرجى مراجعة نوع وقيمة البيانات المدخلة!')
    return HttpResponseRedirect('/retrieve/{}/{}/'.format(targetModel, targetID))

def addData(request, model):
    AddForms = {'company': AddCompanyForm, 'category': AddCategoryForm, 'department': AddDepartmentForm, 'invoice': AddInvoiceForm}
    if request.method == 'POST':
        form = AddForms[model](request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'تم إضافة البيانات بنجاح!')
        else:
            messages.warning(request, 'لم يتم إضافة البيانات، يرجى مراجعة نوع وقيمة البيانات المدخلة!')
        # if a GET (or any other method) we'll create a blank form
    else:
        messages.warning(request, 'لم يتم إضافة البيانات، يرجى مراجعة نوع وقيمة البيانات المدخلة!')
    return HttpResponseRedirect('/add-{}.html#'.format(model))

apps/templates/invoice/add-invoice.html
{% extends "layouts/base-invoice.html" %}

{% load static %}

{% block title %} إضافة فاتورة {% endblock %} 

{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

	{% comment %} [ Main Content ] start {% endcomment %}
	<div class="pcoded-main-container">
		<div class="pcoded-content">
			{% comment %} [ breadcrumb ] start {% endcomment %}
			<div class="page-header">
				<div class="page-block">
					<div class="row align-items-center">
						<div class="col-md-12">
							<div class="page-header-title">
								<h5 class="m-b-10">إضافة فاتورة</h5>
							</div>
							<ul class="breadcrumb">
								<li class="breadcrumb-item"><a href="/invoice/"><i class="feather icon-home"></i></a></li>
								<li class="breadcrumb-item"><a href="#">إدخال الفواتير</a></li>
								<li class="breadcrumb-item"><a href="#">إضافة فاتورة</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			{% comment %} [ breadcrumb ] end {% endcomment %}
			{% comment %} [ Main Content ] start {% endcomment %}
			<div class="row">
				{% comment %} [ sample-page ] start {% endcomment %}
				<div class="col-sm-12">
					{% if messages %}
					<div class="messages">
						{% for message in messages %}
						<div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
						{% endfor %}
					</div>
					{% endif %}
					<form action="#details" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						<div class="card">
							<div class="card-header">
								<h5>معلومات الفاتورة</h5>
							</div>
							<div class="card-body">
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon2">الجهة المصدرة للفاتورة</span>
									</div>
									{{ invoice_form.company }}
									<div class="invalid-feedback">Example invalid custom select feedback</div>
									<small id="passwordHelpBlock" class="form-text text-muted w-100">
										في حال عدم وجود اسم الجهة المصدرة في قائمة الشركات أعلاه أو في حال عدم مطابقة رقم السجل التجاري يجب الرجوع لفرع النظم.
									</small>
								</div>
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon2">رقم الفاتورة</span>
									</div>
									{{ invoice_form.number }}
								</div>
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon2">تاريخ الفاتورة</span>
									</div>
									{{ invoice_form.purchase_date }}
								</div>
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon2">تصنيف الفاتورة</span>
									</div>
									{{ invoice_form.category }}
								</div>
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon2">فاتورة موجهة لقسم</span>
									</div>
									{{ invoice_form.department }}
								</div>
								<div class="input-group mb-3">
									<div class="input-group-prepend w-25">
										<span class="input-group-text" id="basic-addon2">صورة ضوئية للفاتورة</span>
									</div>
									{% if invoice_image %}
									<button class="btn btn-primary w-50" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">عرض المستند الحالي</button>
									<a class="w-25" href="{% url 'home:delete-image' inv_slug=inv_slug %}">
										<button class="btn btn-danger w-100" type="button">
											تغيير المستند
										</button>
									</a>
									<div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions" aria-labelledby="offcanvasWithBothOptionsLabel">
										<div class="offcanvas-header">
											<h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">صورة ضوئية للفاتورة</h5>
											<button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
										</div>
										<div class="offcanvas-body">
											<img src="{% static invoice_image %}" class="img-fluid" alt="صورة ضوئية للفاتورة">
											{{ invoice_image }}
										</div>
									</div>
									{% else %}
									{{ invoice_form.img }}
									{% endif %}
								</div>
							</div>
							<div class="card-body">
								<div class="input-group mb-3">
									<div class="input-group-prepend col-2">
										<span class="input-group-text">إدخال البيانات</span>
									</div>
									<div class="custom-file col-8">
										<input type="text" name="entryPerson" maxlength="100" class="form-control" readonly="" id="id_entryPerson" value="{{ user.get_full_name }}">
									</div>
									<div class="input-group-append col-2">
										<a href="{% url 'logout' %}">
											<button class="btn btn-danger w-100" type="button">
												تغيير الحساب
											</button>
										</a>
									</div>
								</div>
								<div class="col-6 mx-auto text-center">
									<button class="btn  btn-success w-50" type="submit">حفظ معلومات الفاتورة</button>
									<button class="btn  btn-warning w-25" type="reset">إعادة تعيين</button>
								</div>
							</div>
						</div>
						{% if invoice.number %}
						<div id="details" class="card">
							<div class="card-header">
								<h5>تفاصيل الفاتورة</h5>
							</div>
							<div class="card-body">
								<button href="#addItemModal" type="button" class="btn btn-link" data-bs-toggle="modal">
									<i class="fa fa-plus-circle" style="color: green;" aria-hidden="true"></i>
									إضافة صنف
								</button>
								{% if items|length > 0 %}
								<div class="table-responsive">
									<table class="table table-hover text-center">
										<thead>
											<tr>
												<th>#</th>
												<th>الصنف</th>
												<th>الوصف</th>
												<th>الكمية</th>
												<th>سعر الوحدة</th>
												<th>السعر الإجمالي</th>
												<th>حذف؟</th>
											</tr>
										</thead>
										<tbody>
											{% for item in items %}
											<tr>
												<td>
													{{ forloop.counter }}
												</td>
												<td>
													{{ item.name }}
												</td>
												<td>
													{{ item.description }}
												</td>
												<td>
													{{ item.quantity }}
												</td>
												<td>
													{{ item.price }}
												</td>
												<td>
													{{ item.total_price }}
												</td>
												<td>
													<a href="{% url 'home:delete-item' slug=item.slug  inv_slug=inv_slug %}">
														<i class="fa fa-times-circle" style="color: red;" aria-hidden="true"></i>
													</a>
												</td>
											</tr>
											{% endfor %}
										</tbody>
										<tfoot>
											<tr>
												<th colspan="3">عدد الأصناف</th>
												<th colspan="4">{{ items_count }}</th>
											</tr>
											<tr>
												<th colspan="3">إجمالي سعر الأصناف</th>
												<th colspan="4">{{ items_total }}</th>
											</tr>
											<tr>
												<th colspan="3">ضريبة القيمة المضافة (14%)</th>
												<th colspan="4">{{ items_tax }}</th>
											</tr>
											<tr>
												<th colspan="3">إجمالي الفاتورة</th>
												<th colspan="4">{{ items_inv }}</th>
											</tr>
										</tfoot>
									</table>
								</div>
								{% endif %}
							</div>
						</div>
						{% endif %}
					</form>
					{% if items|length > 0 %}
					<form action="#" method="post">
						{% csrf_token %}
						<div class="card">
							<div class="card-header">
								<h5>حفظ وإرسال الفاتورة</h5>
							</div>
							<div class="card-body">
								<div class="input-group mb-3">
									<div class="input-group-prepend">
										<span class="input-group-text" id="basic-addon2">أضف ملاحظة</span>
									</div>
									{{ comment_form.detail }}
								</div>
								<div class="custom-control custom-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" id="customControlValidation1" required>
									<label class="custom-control-label" for="customControlValidation1">أقر بأني قمت بمراجعة كافة معلومات وتفاصيل الفاتورة بشكل دقيق وأنني استخدم المنظومة بحسابي الخاص بي ويظهر اسم المستخدم الخاص بي أعلاه وليس اسم شخص آخر ...</label>
								</div>
								<div class="col-6 mx-auto text-center">
									<button class="btn  btn-primary w-50" type="submit">إرسال الفاتورة للمراجعة</button>
								</div>
								{% if comments|length > 0 %}
								<div class="card mt-5">
									<div class="card-header">
										<h5>ملاحظات مسجلة:</h5>
									</div>
									{% for comment in comments %}
									<div class="card-footer text-muted text-end pb-0">
										{{ comment.date_created }}
									</div>
									<div class="card-body text-center pt-0">
										<h5 class="card-title">{{ comment.entryPerson }}</h5>
										<p class="card-text">{{ comment.detail }}</p>
									</div>
									<hr>
									{% endfor %}
								</div>
								{% endif %}
							</div>
						</div>
					</form>
					{% endif %}
				</div>
				{% comment %} [ sample-page ] end {% endcomment %}
			</div>
			{% comment %} [ Main Content ] end {% endcomment %}
		</div>
	</div>
	{% comment %} [ Main Content ] end {% endcomment %}
	<div class="modal modal-sheet py-5" tabindex="-1" id="addItemModal">
		<div class="modal-dialog">
			<div class="modal-content rounded-6 shadow">
				<form action="#details" method="post">
				{% csrf_token %}
				<div class="modal-header border-bottom-0">
					<h5 class="modal-title">إضافة صنف للفاتورة</h5>
					<button type="button" class="btn-close ms-auto me-0" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body py-0">
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon2">اسم</span>
						</div>
						{{item_form.name}}
					</div>
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon2">وصف</span>
						</div>
						{{item_form.description}}
					</div>
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon2">كمية</span>
						</div>
						{{item_form.quantity}}
					</div>
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon2">سعر</span>
						</div>
						{{item_form.price}}
					</div>
				</div>
				<div class="modal-footer flex-column border-top-0">
					<button type="submit" class="btn btn-lg btn-primary w-100 mx-0 mb-2">أضف للفاتورة</button>
				</div>
				</form>
			</div>
		</div>
	</div>

{% endblock content %}

{% comment %} Specific Page JS goes HERE  {% endcomment %}
{% block javascripts %}
<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/calendar.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/assets/js/DateTimeShortcuts.js"></script>
<script src="/static/admin/js/core.js"></script>
<script>
	window.onload = function() {
		document.getElementById('calendarlink0').innerHTML = '<i class="feather icon-calendar"></i>';
	};
</script>
{% endblock javascripts %}